version: '3.1'
services:
  odoo:
    image: odoo:17  # Indica que usará la imagen oficial de Odoo versión 17.
    ports:
      - "8069:8069"  # Expone el puerto 8069 para acceder a Odoo desde el navegador.
    environment:
      - HOST=db  # Define el nombre del servicio que actúa como base de datos.
    depends_on:
      - db  # Asegura que el contenedor de PostgreSQL esté corriendo antes de iniciar Odoo.
    volumes:
      - ./addons:/mnt/extra-addons  # Mapea la carpeta local `addons` como carpeta de addons personalizados.

  db:
    image: postgres:17  # Utiliza la imagen oficial de PostgreSQL versión 13.
    environment:
      POSTGRES_USER: odoo_user  # Define el usuario para PostgreSQL.
      POSTGRES_PASSWORD: Pelotas@1457  # Contraseña del usuario.
      POSTGRES_DB: odoo_db  # Nombre de la base de datos predeterminada.

volumes:
  db_data: {}  # Crea un volumen para persistir los datos de la base de datos.